// src/constants/roles.js
module.exports = {
  ETUDIANT: 'ETUDIANT',
  SECRETAIRE_ADJOINT: 'SECRETAIRE_ADJOINT',
  SECRETAIRE_GENERAL: 'SECRETAIRE_GENERAL',
  CHEF_DIVISION: 'CHEF_DIVISION',
  DIRECTEUR_ADJOINT: 'DIRECTEUR_ADJOINT',
  DIRECTEUR: 'DIRECTEUR',
  SUPER_ADMIN: 'SUPER_ADMIN',
};