// src/constants/statuts.js
module.exports = {
  // StatutDemande
  SOUMISE: 'SOUMISE',
  CORRECTION_DEMANDEE: 'CORRECTION_DEMANDEE',
  TRANSMISE_SECRETAIRE_ADJOINT: 'TRANSMISE_SECRETAIRE_ADJOINT',
  TRANSMISE_SECRETAIRE_GENERAL: 'TRANSMISE_SECRETAIRE_GENERAL',
  DOCUMENT_GENERE: 'DOCUMENT_GENERE',
  ATTENTE_VALIDATION_DA: 'ATTENTE_VALIDATION_DA',
  ATTENTE_SIGNATURE_DIRECTEUR: 'ATTENTE_SIGNATURE_DIRECTEUR',
  DISPONIBLE: 'DISPONIBLE',
  REJETEE: 'REJETEE',
  ANNULEE: 'ANNULEE',

  // StatutDocument
  DOCUMENT_GENERE: 'DOCUMENT_GENERE',
  ATTENTE_SIGNATURE_DIRECTEUR: 'ATTENTE_SIGNATURE_DIRECTEUR',
  DISPONIBLE: 'DISPONIBLE',
  REJETEE: 'REJETEE',

  // StatutPiece
  SOUMISE: 'SOUMISE',
  VALIDEE: 'VALIDEE',
  REJETEE: 'REJETEE',
};