// src/constants/typeDocument.js
module.exports = {
  ATTESTATION_INSCRIPTION: "ATTESTATION_INSCRIPTION",
  RELEVE_NOTES: "RELEVE_NOTES",
  ATTESTATION_SUCCES: "ATTESTATION_SUCCES",
  ATTESTATION_ADMISSIBILITE: "ATTESTATION_ADMISSIBILITE",
};